# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PeopleMain.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PeopleMain(object):
    def setupUi(self, PeopleMain):
        PeopleMain.setObjectName("PeopleMain")
        PeopleMain.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/crowd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PeopleMain.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(PeopleMain)
        self.centralwidget.setObjectName("centralwidget")
        PeopleMain.setCentralWidget(self.centralwidget)
        self.Menu = QtWidgets.QMenuBar(PeopleMain)
        self.Menu.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.Menu.setObjectName("Menu")
        self.menuFile = QtWidgets.QMenu(self.Menu)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.Menu)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.Menu)
        self.menuHelp.setObjectName("menuHelp")
        self.menuWindows = QtWidgets.QMenu(self.Menu)
        self.menuWindows.setObjectName("menuWindows")
        self.menuPages = QtWidgets.QMenu(self.menuWindows)
        self.menuPages.setObjectName("menuPages")
        self.menuWindowLists = QtWidgets.QMenu(self.menuWindows)
        self.menuWindowLists.setObjectName("menuWindowLists")
        self.menuTools = QtWidgets.QMenu(self.Menu)
        self.menuTools.setObjectName("menuTools")
        self.menuAnatomy = QtWidgets.QMenu(self.Menu)
        self.menuAnatomy.setObjectName("menuAnatomy")
        self.menuMeridians = QtWidgets.QMenu(self.menuAnatomy)
        self.menuMeridians.setObjectName("menuMeridians")
        self.menuPeople = QtWidgets.QMenu(self.Menu)
        self.menuPeople.setObjectName("menuPeople")
        self.menuCrowds = QtWidgets.QMenu(self.menuPeople)
        self.menuCrowds.setObjectName("menuCrowds")
        PeopleMain.setMenuBar(self.Menu)
        self.Status = QtWidgets.QStatusBar(PeopleMain)
        self.Status.setObjectName("Status")
        PeopleMain.setStatusBar(self.Status)
        self.Tools = QtWidgets.QToolBar(PeopleMain)
        self.Tools.setObjectName("Tools")
        PeopleMain.addToolBar(QtCore.Qt.TopToolBarArea, self.Tools)
        self.actionQuit = QtWidgets.QAction(PeopleMain)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon1)
        self.actionQuit.setObjectName("actionQuit")
        self.actionMeridian = QtWidgets.QAction(PeopleMain)
        self.actionMeridian.setObjectName("actionMeridian")
        self.actionAcupunctures = QtWidgets.QAction(PeopleMain)
        self.actionAcupunctures.setObjectName("actionAcupunctures")
        self.actionCrowdListings = QtWidgets.QAction(PeopleMain)
        self.actionCrowdListings.setObjectName("actionCrowdListings")
        self.actionCrowdViews = QtWidgets.QAction(PeopleMain)
        self.actionCrowdViews.setObjectName("actionCrowdViews")
        self.menuFile.addAction(self.actionQuit)
        self.menuWindows.addAction(self.menuPages.menuAction())
        self.menuWindows.addAction(self.menuWindowLists.menuAction())
        self.menuMeridians.addAction(self.actionMeridian)
        self.menuMeridians.addAction(self.actionAcupunctures)
        self.menuAnatomy.addAction(self.menuMeridians.menuAction())
        self.menuCrowds.addAction(self.actionCrowdListings)
        self.menuCrowds.addAction(self.actionCrowdViews)
        self.menuPeople.addAction(self.menuCrowds.menuAction())
        self.Menu.addAction(self.menuFile.menuAction())
        self.Menu.addAction(self.menuEdit.menuAction())
        self.Menu.addAction(self.menuPeople.menuAction())
        self.Menu.addAction(self.menuAnatomy.menuAction())
        self.Menu.addAction(self.menuTools.menuAction())
        self.Menu.addAction(self.menuWindows.menuAction())
        self.Menu.addAction(self.menuHelp.menuAction())
        self.Tools.addAction(self.actionQuit)

        self.retranslateUi(PeopleMain)
        self.actionQuit.triggered.connect(PeopleMain.Quit)
        self.actionMeridian.triggered.connect(PeopleMain.Meridians)
        self.actionAcupunctures.triggered.connect(PeopleMain.Acupunctures)
        self.actionCrowdListings.triggered.connect(PeopleMain.CrowdListings)
        self.actionCrowdViews.triggered.connect(PeopleMain.CrowdViews)
        QtCore.QMetaObject.connectSlotsByName(PeopleMain)

    def retranslateUi(self, PeopleMain):
        _translate = QtCore.QCoreApplication.translate
        PeopleMain.setWindowTitle(_translate("PeopleMain", "People"))
        self.menuFile.setTitle(_translate("PeopleMain", "File"))
        self.menuEdit.setTitle(_translate("PeopleMain", "Edit"))
        self.menuHelp.setTitle(_translate("PeopleMain", "Help"))
        self.menuWindows.setTitle(_translate("PeopleMain", "Windows"))
        self.menuPages.setTitle(_translate("PeopleMain", "Pages"))
        self.menuWindowLists.setTitle(_translate("PeopleMain", "Window listings"))
        self.menuTools.setTitle(_translate("PeopleMain", "Tools"))
        self.menuAnatomy.setTitle(_translate("PeopleMain", "Anatomy"))
        self.menuMeridians.setTitle(_translate("PeopleMain", "Meridians"))
        self.menuPeople.setTitle(_translate("PeopleMain", "People"))
        self.menuCrowds.setTitle(_translate("PeopleMain", "Crowds"))
        self.Tools.setWindowTitle(_translate("PeopleMain", "toolBar"))
        self.actionQuit.setText(_translate("PeopleMain", "Quit"))
        self.actionMeridian.setText(_translate("PeopleMain", "Meridians"))
        self.actionAcupunctures.setText(_translate("PeopleMain", "Acupunctures"))
        self.actionCrowdListings.setText(_translate("PeopleMain", "Listings"))
        self.actionCrowdViews.setText(_translate("PeopleMain", "Views"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PeopleMain = QtWidgets.QMainWindow()
    ui = Ui_PeopleMain()
    ui.setupUi(PeopleMain)
    PeopleMain.show()
    sys.exit(app.exec_())
